### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by mg1075** [karolyi/ui-selectableScroll#6]
This looks great and solves the problem described here: 
http://bugs.jqueryui.com/ticket/4441

But the license you are using basically means no one 
can use this inside of a commercial project, correct?

Seems like the jquery ui guys had the same problem with the license?
http://bugs.jqueryui.com/ticket/3223

**Comment by karolyi** [comment]
I was too lazy to put a proper license to this project, but you can use it for any kind of projects you want. I created this for the opensource community, anyone can have it.

**Comment by mg1075** [comment]
So this **can** be used for commercial projects the way a project with an MIT license could be used?

The end of the conversation in the jQuery UI ticket 3223 indicates the jQuery UI guys were waiting back for a response from you. Your code really fixes their bug, so I would hope the fix goes into their codebase.

![image](https://cloud.githubusercontent.com/assets/2031435/6992876/d892d62e-daa6-11e4-958b-8f0077c437d3.png)

**Comment by karolyi** [comment]
Yes you can use it in commercial projects.

I don't have much time to create a PR for jquery-ui. Besides, it not just 'fixes their bug' but adds functionality so that the selectable can be in a scrollable div where pulling the lasso outside the div would scroll the content.
