### ISSUE TITLE
Auto scroll does not work!

### ISSUE THREAD

**Issue by adominik42** [karolyi/ui-selectableScroll#7]
Using your script, the scroll bar moves, but the page stays the same position.

I have initialized the following way:

attendance_sheet_table.selectable({  
                filter: "tbody tr:not(.not-editable):not(.extended)",
                cancel: "tbody tr.not-editable, tbody tr.extended",
                selected: addSelectedDayToCache,
                unselected: removeSelectedDayFromCache,
                scrollSnapX: 5,
                scrollSnapY: 5,
                scrollAmount: 25,
                scrollIntervalTime: 100
            });

Any idea?

**Comment by karolyi** [comment]
hey,

could you please create a jsfiddle reproducing the bug?

**Comment by karolyi** [comment]
closing this as no feedback on my question arrived.
